# dist: trusty # KVM Setup

# For now only "linux" as it looks like docker
# is not available on "osx"
os:
  - linux

language: go

go:
  - 1.8.3

env:
  - TEST_VERBOSE=1

script:
  - make -C sharness
  - go test ./ipfs-5-to-6/migration/

# For docker containers

sudo: required

services:
  - docker
